### ISSUE TITLE
pretraining

### ISSUE THREAD

**Issue by Nameggy** [ChengpengChen/RepGhost#1]
Can you provide a pre-training weight file? Thanks

**Comment by ChengpengChen** [comment]
We have upload the checkpoints to [GoogleDrive](https://drive.google.com/drive/folders/1aL5UkhXgevyoQDo_cLmmd-DUfZcAFRXu?usp=share_link) actually.

To check the infos of the released models at https://github.com/ChengpengChen/RepGhost#results-and-pre-trained-models
