### ISSUE TITLE
测量模型延迟问题

### ISSUE THREAD

**Issue by ZS-YANG** [ChengpengChen/RepGhost#11]
![image](https://github.com/ChengpengChen/RepGhost/assets/52490943/219d74db-65de-4cd3-80c9-f1c4f1642ec6)
1. 请问表格中RepGhostNet 0.5对应的模型是是这个吗https://github.com/ChengpengChen/RepGhost/blob/main/model/repghost.py#L463
模型中都有se模块的吧
2. 请问作者大大油没有测试过模型在openvino或者tensorrt框架的延迟，如果用openvino框架测量模型延迟，在转换模型的步骤中，需要开启openvino自带的模型优化功能吗？
七夕快乐🌹

**Comment by ChengpengChen** [comment]
你好！感觉你对RepGhost 的关注！

1. 表格中的0.5x 跟code 是对应的。目前所有的RepGhostNet 都有SE，这也跟MobileNetV3 和GhostNet 保持一致。
2. 我们目前没有在openvino上面测试过，欢迎你们扩展更多的应用！对于tensorrt，文章里面有res50+repghost 的结果可以参考；此外，因为RepGhostNet是针对移动端设计的，而tensorrt主要用在GPU部署，因此暂时还没有直接在tensorrt上面测试RepGhostNet 的结果。

**Comment by ZS-YANG** [comment]
好的！感谢回复！
