### ISSUE TITLE
result on yolov5 compare with yolov5-tiny?

### ISSUE THREAD

**Issue by lucasjinreal** [ChengpengChen/RepGhost#3]
hi, any exp result on comparasion with yolov5? Retinanet itself didn't quite fast on mobile platform.
How about mAP compare with yolov5-tiny?

**Comment by ChengpengChen** [comment]
We have not evaluate yolov5  with our RepGhostNet as backbone yet. It would be straight to do this, that is, replacing the pretrained backbone directly and starting your training.

Note that we have released the pretrained models, please feel free to use RepGhsotNet for any wonderful things you want and we would be grateful if you could share your results with us.

**Comment by lucasjinreal** [comment]
@ChengpengChen The reason why I ask, is that RepGhost compare with some **very old** lightweighted backbone and didn't get a very impressive AP boost on detection task.

Some SOTA lightweighted backbone such as TinyNet, MobileOne, CSPDarknet-Tiny should far more convincing than just mobilenetv2 .

Especially MobileOne, it's using same technical with  Repparams

**Comment by ChengpengChen** [comment]
Hi, jinfagang,
I get your concern. But notice that our experiments are all under strict control, such as similar FLOPs or latency for each backbone, to verify the effectiveness and efficiency of our method.

It seems that the **very impressive AP boost** you mean in MobileOne does not work in this way, such as Table 9 in MobileOne paper, MobileOne-S1 (825M) gets better performance than MobileNetV2 (300M), but not impressively (3.6 mAP in COCO, 1.6mIoU in VOC and 1.0mIoU in ADE20k gains but with almost 3 times the cost). And MobileOne-S0 (275M) is worse than MobileNetV2 in these tasks. Besides, all MobileOne models are much slower in our evaluation.

As for TinyNet and CSPDarknet-Tiny, we have not compare them to our networks yet. It would be interesting to work on this :)

**Comment by lucasjinreal** [comment]
@ChengpengChen Indeed. If am not wrong, repghost eliminated the 2 cat op in very single neck used. But for params it should not be count in, so actually repghost is much more faster then ghost neverthless higher accuracy, is that right?

**Comment by ChengpengChen** [comment]
Yep, you got it.
Our method focuses on improving efficiency of light-weight CNNs via re-parameterization.
